language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t willyhui94/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true willyhui94/docker-react yarn run test -- --coverage

deploy:
  provide: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-850450556145'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
